# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RecipesApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'Alamofire', '5.0.0-beta.3'
  pod 'BrightFutures'
  pod 'ReachabilitySwift'
  pod 'KeychainSwift'


  # Pods for RecipesApp

end
