// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

namespace WebApi.Data.Migrations
{
    [DbContext(typeof(RecipesContext))]
    [Migration("20210411232501_M1")]
    partial class M1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi.Models.Ingredient", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Recipeid")
                        .HasColumnType("int");

                    b.Property<int>("carbohydrates")
                        .HasColumnType("int");

                    b.Property<int>("fats")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("proteins")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Recipeid");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("WebApi.Models.Menue", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("id");

                    b.ToTable("Menues");
                });

            modelBuilder.Entity("WebApi.Models.Recipe", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Menueid")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("id");

                    b.HasIndex("Menueid");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("WebApi.Models.Ingredient", b =>
                {
                    b.HasOne("WebApi.Models.Recipe", null)
                        .WithMany("ingredients")
                        .HasForeignKey("Recipeid");
                });

            modelBuilder.Entity("WebApi.Models.Recipe", b =>
                {
                    b.HasOne("WebApi.Models.Menue", null)
                        .WithMany("recipes")
                        .HasForeignKey("Menueid");
                });

            modelBuilder.Entity("WebApi.Models.Menue", b =>
                {
                    b.Navigation("recipes");
                });

            modelBuilder.Entity("WebApi.Models.Recipe", b =>
                {
                    b.Navigation("ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
